version: '3.8'

services:
  crm:
    build: .
    container_name: probolsas_crm
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crm.rule=Host(`crm.probolsas.co`)"
      - "traefik.http.routers.crm.entrypoints=websecure"
      - "traefik.http.routers.crm.tls=true"
      - "traefik.http.services.crm.loadbalancer.server.port=3000"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true